### ISSUE TITLE
Update action to Github Actions v2

### ISSUE THREAD

**Issue by tiagobrito** [stefanzweifel/git-auto-commit-action#1]
This Action doesn't  seem to work with new GH workflow format

**Comment by stefanzweifel** [comment]
Hi folks 👋

Sorry for the late response. Somehow I wasn't watching this repo and didn't get a notification for this issue.

I just got access to the new beta and can reproduce your error. Don't understand yet, why this happens … so any helps is greatly appreciated!

**Comment by stefanzweifel** [comment]
Closing this issue, as it's a duplicate of #2
