### ISSUE TITLE
Use a default commit message if one isn't provided

### ISSUE THREAD

**Issue by fregante** [stefanzweifel/git-auto-commit-action#103]
**Is your feature request related to a problem? Please describe.**

Currently `commit_message` is a required input. Given how verbose workflows can be, I prefer not having to specify any inputs when possible.

**Describe the solution you'd like**

If `commit_message` isn't specified, it should use a default message. Anything generic works. The  "Apply automatic changes" message suggested by the readme would also be fine.

I'm open to submit a PR for this.

**Comment by stefanzweifel** [comment]
The idea behind this, is that you can simply add this line to your workflows and be done with it, right?

```
- uses: stefanzweifel/git-auto-commit-action@v4
```

I think thats actually not a bad idea. "Apply automatic changes" might be a good starting point.
However I would like to encurage users in the README to set their own value.

Feel free to PR this. 
Updating the following lines accordingly should do the trick:
https://github.com/stefanzweifel/git-auto-commit-action/blob/master/action.yml#L7-L9

**Comment by stefanzweifel** [comment]
Has been implemented in #110.
I will tag a new version soon.
