### ISSUE TITLE
Run test suite, file missing

### ISSUE THREAD

**Issue by francescobianco** [stefanzweifel/git-auto-commit-action#112]
**Version of the Action**
`v4.x.x`

**Describe the bug**
Where the file `shellmock` is?

**To Reproduce**
1. Go to terminal into the project directory
2. Run `npm install`
3. Run `npm run test`
4. Some tests fail for missing file `shellmock` 

**Expected behavior**
All tests pass by default.

**Comment by stefanzweifel** [comment]
Thanks for reporting.
Unfortunately `shellmock` can't be installed through NPM. :( 

On CI we just clone the repo and run their install script. ([GitHub Actions Workflow](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/.github/workflows/tests.yml#L14-L16))

I will add a `setup.sh` script or something, which will setup everything required to run the tests locally.

**Comment by stefanzweifel** [comment]
This took a bit longer than expected.
I've rewritten the test suite in #128 to no longer mock `git`. The tests can now be run by simply installing the testing dependencies with `yarn` or `npm` and then running `yarn test` or `npm run test`.

The README has been slightly updated to indicate, that node dependencies have to be installed.
https://github.com/stefanzweifel/git-auto-commit-action#running-the-tests
