### ISSUE TITLE
[FEATURE REQUEST] Support custom file pattern

### ISSUE THREAD

**Issue by gomorizsolt** [stefanzweifel/git-auto-commit-action#12]
There might be some cases when:
- the user isn't entirely sure what additional files the workflow/job outputs
- or just simply wouldn't like to push certain changes, e.g. to `master`

Wouldn't it be beneficial to accept an optional param to support customizing the file pattern? As I see, specifying the files leads to a much more reliable action.

**Comment by gomorizsolt** [comment]
I'm glad to hear that. To tell the truth, I'm not used to working with docker-based environments - it's actually still something to be crossed off my "bucket list". However, I'd appreciate if you could help me out to learn something new today.

At first glance, it's seemingly as simple as replacing `git add .` with something like `git add $INPUT`. However, where do the `INPUT_BRANCH` and `INPUT_COMMIT_MESSAGE` come from in `entrypoint.sh`? Does docker set `branch` and `commit_message` to these values in the background?

Though it's most likely to be a minor improvement, but it seems to be a bit redundant to mention the input params in `README.md`. If I'm allowed to give a little piece of advice, then IMO it'd make sense to reference `action.yml` instead as it should already give a clear overview about the required/not required params.

**Comment by stefanzweifel** [comment]
> At first glance, it's seemingly as simple as replacing git add . with something like git add $INPUT

Yeah, that would be my approach too.
(I mostly work with a GUI Git client, so I'm also not that much of an expert with git.)

> However, where do the INPUT_BRANCH and INPUT_COMMIT_MESSAGE come from in entrypoint.sh? Does docker map/set branch and commit_message to these values in the background?

As you might have already noticed, the values come from the [`actions.yml`](https://github.com/stefanzweifel/git-auto-commit-action/blob/9fc8aa621f330634026f7622b64947c62adb6a74/actions.yml#L7-L12)-file.
GitHub Actions automatically translates those into environment variables which are then available in the docker "context". (See [docs](https://help.github.com/en/github/automating-your-workflow-with-githu) for more).

So the easiest solution would be adding a new `file_pattern` input and then referencing that in `entrypoint.sh` as `$INPUT_FILE_PATTERN`.




> Though it's most likely to be a minor improvement, but it seems to be a bit redundant to mention the input params in README.md. If I'm allowed to give a little piece of advice, then IMO it'd make sense to reference action.yml instead as it should already give a clear overview about the required/not required params.

Thanks for the idea. That's probably a habit of mine I've created while developing other packages 😅.
Originally this Action had a lot more inputs. I will skim through the README and improve it over the coming days/weeks.

**Comment by stefanzweifel** [comment]
I just ran into this issue, where the Action should only add a glob of files. Will tinker on this over the next few days.

**Comment by stefanzweifel** [comment]
@gomorizsolt Just opened a PR with a new `file_input` option with which you can change how `git add` works.

Here's an example to only add changed js-files in the `src`-directory.

```
    - uses: stefanzweifel/git-auto-commit-action@add-file-pattern
      with:
        commit_message: Your message
        branch: ${{ github.head_ref }}
        file_pattern: src/\*.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by gomorizsolt** [comment]
@stefanzweifel Sorry for the late response, had a busy day today.

> (See docs for more).

Actually the referenced URL is broken, though it wasn't that tough to find the relevant context in the docs. It seems I've totally overlooked this specification.

> When you specify an input to an action in a workflow file or use a default input value, GitHub creates an environment variable for the input with the name INPUT_<VARIABLE_NAME>.

> That's probably a habit of mine I've created while developing other packages 😅.

Sure, it's your choice.

> Just opened a PR with a new file_input option with which you can change how git add works.

Cool! Overall looks great, left a few comments.

**Comment by gomorizsolt** [comment]
@stefanzweifel Thanks for implementing the feature, I appreciate it.

I've been struggling with passing the default `file_pattern` param towards the Docker container for a while but it's seemingly not that intuitive/simple as it seems to be. I've stumbled upon the [`args`](https://help.github.com/en/github/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#args) option but it couldn't solve the issue at all - it's likely to be useful in a different scenario. Even though the requested feature does already work, I'll definitely devote more effort/time to explore what's the root cause of this unexpected behavior.
