### ISSUE TITLE
[FEATURE REQUEST] Support custom git params

### ISSUE THREAD

**Issue by gomorizsolt** [stefanzweifel/git-auto-commit-action#14]
Our team uses [`pre-commit`](https://github.com/observing/pre-commit) to ensure certain tests pass before committing the changes. However, in some cases, it's unnecessary to run these scripts(e.g. when editing `README.md`) and so we're able to skip them by appending the `--no-verify` param to the command.

**Example**

```bash
git commit -m "John Doe" --no-verify
```

What's your opinion on this feature? Can you see any security issue?

**Comment by gomorizsolt** [comment]
> However, if you have some critical checks in your pre-commit-settings and you decided to ignore those with --no-verify and something bad happens … that's a decision the user made 🤷‍♂.

Yes, that's rather sort of a responsibility on the user's side to control the arguments passed into the command.

Thanks for the quick feedback and suggestions, I'll submit a PR soon.

**Comment by stefanzweifel** [comment]
> Thanks for the quick feedback and suggestions, I'll submit a PR soon.

Thank you for the great ideas!
