### ISSUE TITLE
Support for Git LFS

### ISSUE THREAD

**Issue by jkaan** [stefanzweifel/git-auto-commit-action#20]
Hi there! I am wondering if it is possible to support Git LFS with this tool.
 
Is there a way that I could overwrite the Dockerfile or something so that I could install Git LFS before?

**Comment by stefanzweifel** [comment]
Hi Joey 👋

The only way you currently could do that is by forking the repo and update the Dockerfile and using your forks in GitHub Actions.

However, I'm open for pull requests. Git LFS supports seems something a lot of people could be using.

I haven't looked into Git LFS yet: Is there a drawback when LFS is installed globally? Maybe we can add an option flag like `enable_lfs` and only when the value is set to true, LFS is installed.

**Comment by stefanzweifel** [comment]
Reading through the Git LFS [docs](https://git-lfs.github.com) there doesn't seem to be a problem, when we install LFS in repositories which do not have a LFS configurations.

As LFS configuration is stored in `.gitattributes`, we also don't have to expose a new configuration, where users would have to define, which file extensions they want to track in LFS.

Feel free to open a PR to update the Dockerfile; or I will look into this more next week.

**Comment by jkaan** [comment]
@stefanzweifel What a fast response! I'll make a PR for it, should not be that much work.

**Comment by stefanzweifel** [comment]
Fixed in #21
