### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by SevereCloud** [stefanzweifel/git-auto-commit-action#246]
### git-auto-commit Version

v4.15.0

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: stefanzweifel/git-auto-commit-action

### Steps to reproduce

Run and see annotations

### Example Workflow

```yaml
-
```

**Comment by stefanzweifel** [comment]
Thanks for bringing this up. Will push an update in the next few hours.

**Comment by stefanzweifel** [comment]
Fixed in v4.15.1: https://github.com/stefanzweifel/git-auto-commit-action/releases/tag/v4.15.1

**Comment by lukasz-mitka** [comment]
@stefanzweifel I advice doing a major release instead and pointing `v4` tag back to `v4.15.0`
Node upgrade can brake this action for self-hosted runners or GHES that haven't upgraded yet.
