### ISSUE TITLE
Github Authentication issues

### ISSUE THREAD

**Issue by yelizariev** [stefanzweifel/git-auto-commit-action#28]
**Version of the Action**
`v2.x.x`

**Describe the bug**
The current implementation doesn't allow us to push a commit to repo branch in a way that triggers updating Github Pages content.

Potentially related issue is described here: https://github.com/stefanzweifel/git-auto-commit-action/pull/26#issuecomment-571134268, but let's focus on Github Pages first

**To Reproduce**

I played with it here: https://github.com/it-projects-llc/shhvshhshhshh-rukovodstvo-polzovatelia/blob/13.0/.github/workflows/rebuild.yml

**Additional context**
https://github.com/stefanzweifel/git-auto-commit-action/pull/26#issuecomment-571054650

**Comment by yelizariev** [comment]
With regards to https://github.com/stefanzweifel/git-auto-commit-action/pull/26#issuecomment-571189950

> I'm open to change how the authentication works.
> Which version do you prefer now?
> 
> Version A:
> 
> https://${process.env.GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${process.env.GITHUB_REPOSITORY}.git
> Version B:
> 
> https://${GH_PAT:-"x-access-token:$GITHUB_TOKEN"}@github.com/${GITHUB_REPOSITORY}.git
> 

It seems that GITHUB_ACTOR is ignored by Github anyway, so the Version B looks cleaner

**Comment by stefanzweifel** [comment]
Closed as #36  has been merged into the `v3` branch. GitHub authentication is now handled by `actions/checkout@v2`.
