### ISSUE TITLE
Author and Commiter

### ISSUE THREAD

**Issue by yelizariev** [stefanzweifel/git-auto-commit-action#29]
There are two main use cases and corresponding ways to sign a commit:

# _Branch Style_
Author=Commiter=Custom User
Example: https://github.com/yelizariev/git-auto-commit-action-demo-app/commit/ac6919746c4b5582dd0328a86ed25f9cb8677283

# _PR Style_

Author=_Actor_
Commiter=_GitHub Actions_
Example: https://github.com/yelizariev/git-auto-commit-action-demo-app/commit/fcee21eb951bc528cc2912e69c215b44723c2d96

---

The questions to discuss:

* Do we agree about described use cases? I.e. do we need another _style_, e.g. Author=Commiter=_Github Actions_
* Do we want to support both styles in the Action?
* If yes, how to allow both styles? What could be the configs for it (config name, default values, etc.)

**Comment by yelizariev** [comment]
I suggest following solution:

1. Add two optional action args:
```
    commit_author_name: "My Bot"
    commit_author_email: "bot@example.com"
```

2. If the args are set, use them both for Author and Committer

3. If the args are not set, compute author and committer depending on ``GITHUB_EVENT_NAME``

   3.1. For pull_request:   
          Keep as it works now, i.e.

          > Author=Actor
          > Commiter=GitHub Actions

   3.2. For push and other events: 

          > Author=Commiter=GitHub Actions

**Comment by yelizariev** [comment]
@stefanzweifel did you have a chance to check my suggestion: https://github.com/stefanzweifel/git-auto-commit-action/issues/29#issuecomment-571468391 ? After such an update, it would work the same way for pull requests by default

**Comment by stefanzweifel** [comment]
@yelizariev Sorry mate, life got in the way the last few days.

+1 for the new optional `commit_author_*` inputs. However, I would keep the logic around them a bit simpler.

If no value has been passed by a user, the values should be `$GITHUB_ACTOR <$GITHUB_ACTOR@users.noreply.github.com>` (Independent of any GitHub events).

I would also like to keep the committer to be "GitHub Actions actions@github.com". My idea behind the committer/author split was to allow users to differentiate commits which have been created by Actions.

Could you maybe describe more, why you would like to have different author/committer logic depending on GitHub events?
Or why you want to remove the differentiation between author and committer? Did that break your workflows?

**Comment by yelizariev** [comment]
Here is the explanation of my desigin.

# Author=Commiter=Custom Value
The idea is to fully "brand" commit with custom "Bot" (technically, I just create another github user). Imagine there is a repo "jedi-tools" and some CI\CD bot named "R2D2". The maintainers may not want to have "Github Actions" Name\Avatar along with R2D2

<img src="https://user-images.githubusercontent.com/186131/72325407-da309000-36ce-11ea-8037-5eb2fec7b787.png" width="50" height="50"> <img src="https://user-images.githubusercontent.com/186131/72325387-cedd6480-36ce-11ea-8ec9-8ec9b69c9c39.png" width="50" height="50"> 

vs

<img src="https://user-images.githubusercontent.com/186131/72325407-da309000-36ce-11ea-8037-5eb2fec7b787.png" width="50" height="50">

I understand your idea to mention "Github Actions" in the commit, but I prefer to do it explicitly in commit message. [example](https://github.com/it-projects-llc/shhvshhshh/commit/d2d9f26e86523f9ef41774b0575dc6ad4110e73f):

> :alien: update translation files
> Sent from Github Actions (see .github/workflows/translations.yml )
 
Also, the maintainer would want to hide reference to Github Actions and use some funny commit description.
 
# Author=Actor

This seems ok for Pull Request. Not sure about Branches. Do you know which value for GITHUB_ACTOR is used on branches? Does it refer to a one who made a push? If so, then it's ok for branches too. I first understanding was that it's the owner of the repository

**Comment by yelizariev** [comment]
Adjusted suggestion
---

I suggest following solution:

1. Add two optional action args:
```
    commit_author_name: "My Bot"
    commit_author_email: "bot@example.com"
```

2. If the args are set, then

    > Author = Commiter = Custom 

3. If the args are not set, then

    > Author=Actor
    > Commiter=GitHub Actions

**Comment by stefanzweifel** [comment]
> Do you know which value for GITHUB_ACTOR is used on branches?

That is always the user which made the push.
From the [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables):

> The name of the person or app that initiated the workflow. For example, octocat.

----

> I suggest following solution

Yeah, I think this is the way forward. I'm going to create a PR to implement this (hopefully over the next days).
And sorry for the dragged out discussion here in the issues. I hope I can answer questions faster/more frequent after January is over.
