### ISSUE TITLE
globbing syntax is limited

### ISSUE THREAD

**Issue by xxxserxxx** [stefanzweifel/git-auto-commit-action#51]
**Version of the Action**
v4.1.0

**Describe the bug**
Maybe this only requires a bit more documentation.  However, it's not clear which syntax file_pattern uses, and under what conditions.  Is it a bash glob?  Or some other language?  Why are the asterixes escaped? The bash syntax `\{\*\*/PKGBUILD,\*\*/.SRCINFO\}` does not work (escaped out so Workflows doesn't complain about the syntax), and neither does `\*\*/PKGBUILD \*\*/.SRCINFO` or any combination of syntax I've tried.  Wrapping the glob in quotes, various permutations of escaping; I've tried several things.

Curiously, I **can** see globbing working, except it fails somehow when actually doing the git commit.  In many cases, I get errors like:

```
INPUT_BRANCH value: 
M	aur-bin/.SRCINFO
M	aur-bin/PKGBUILD
M	aur/.SRCINFO
M	aur/PKGBUILD
Your branch is up to date with 'origin/master'.
INPUT_FILE_PATTERN: \{\*\*/PKGBUILD,\*\*/.SRCINFO\}
fatal: pathspec '\{\*\*/PKGBUILD,\*\*/.SRCINFO\}' did not match any files
```
so the log message is actually getting a proper glob list, but it fails in the actual message.

It'd be great to get some documentation about what is legal glob syntax, and maybe another example of non-trivial globbing.  In my case, I'm looking for the result of the bash glob pattern:
```
{**/PKGBUILD,**/.SRCINFO}
```

**To Reproduce**
Make a project in github called `globtest`
```
mkdir -p dummy/A dummy/B dummy/.github/workflows/
pushd dummy
touch A/x A/y B/x B/y
cat > .github/workflows/dummy.yml <<EOL
name: dummy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        shell: bash
        run: echo 1 > A/x ; echo 2 > A/y ; echo 3 > B/x ; echo 4 > B/y
      - uses: stefanzweifel/git-auto-commit-action@v4.1.0
        with:
            commit_message: Message
            file_pattern: \{\*\*/x,\*\*/y\}
EOL
git init && git add . && git commit -m "X"
git remote add origin git@github.com:stefanzweifel/globtest.git
git push -f origin master
touch me && git commit -a -m "foo" && git push
```

**Expected behavior**
All changed files to be committed.

I didn't try any of that blob of steps above, so YMMV. But you get the idea.

**Comment by stefanzweifel** [comment]
Thanks for writing such a detailed issue! I'm grateful when users write such detailed  descriptions of their problems. 

> However, it's not clear which syntax file_pattern uses, and under what conditions. Is it a bash glob? Or some other language? Why are the asterixes escaped?

The syntax used is whatever `git` uses. In the `git-add` documentation the option is called `pathspec` ([`pathspec` documentation](https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203)).
In [their gloassary](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec) there's even more information. There, they don't seem to escape the asterix.

It seems, this might be a documentation issue on our side for this Action. However, in #13, when the feature was added, I could successfully test the Action with the `src/\*.js` pattern.

**Comment by xxxserxxx** [comment]
@stefanzweifel  The trivial example does work.  Is git being run in a bash instance?  Is it making an API call to git, or is it executing a command in some shell environment?

Thanks for the pointers to the pathspec; that does help.  Do you know the escaping rules?  Is the escaping only for workflows, so the engine doesn't choke on the arguments, or is it for the environment git is running in?

**Comment by stefanzweifel** [comment]
>  Is git being run in a bash instance? Is it making an API call to git, or is it executing a command in some shell environment?

I honestly don't know how to answer that question correctly. All I can tell is that the `git`-cli is executed on the command line in some shell environment. If you've chosen to run the Workflow on a linux machine, I guess it's `bash`.

> Do you know the escaping rules? Is the escaping only for workflows, so the engine doesn't choke on the arguments, or is it for the environment git is running in?

I don't know the escaping rules, sorry.
Maybe the docs for GitHub Actions can help you further. I highly recommend reading *all* pages of them.

- https://help.github.com/en/actions
- https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners

**Comment by cristianpb** [comment]
I had the same issue when adding multiple files.

Replacing line https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L48

`git add "${INPUT_FILE_PATTERN}"` 

by

`git add ${INPUT_FILE_PATTERN}`

solves the issue.

Should I made a PR @stefanzweifel ?

**Comment by stefanzweifel** [comment]
@cristianpb That would be great.

**Comment by vikyd** [comment]
> Thanks for writing such a detailed issue! I'm grateful when users write such detailed descriptions of their problems.
> 
> > However, it's not clear which syntax file_pattern uses, and under what conditions. Is it a bash glob? Or some other language? Why are the asterixes escaped?
> 
> The syntax used is whatever `git` uses. In the `git-add` documentation the option is called `pathspec` ([`pathspec` documentation](https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203)).
> In [their gloassary](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec) there's even more information. There, they don't seem to escape the asterix.
> 
> It seems, this might be a documentation issue on our side for this Action. However, in #13, when the feature was added, I could successfully test the Action with the `src/\*.js` pattern.



-----

In my case `file_pattern: ./\*.md` is not woking. Don't know why.

**Comment by stefanzweifel** [comment]
@vikyd What exactly do you wanna achieve?

To add all changed markdown files use `file_pattern: *.md`
To only add changed markdown files in subfolders use `file_pattern: */*.md`.

**Comment by cristianpb** [comment]
@vikyd you can also just do something custom, like:

```yaml
      - name: Auto commit
        run: |
          git config --global user.name 'Github Bot'
          git config --global user.email 'bot@github.com'
          git add *.md
          git commit -m "⬆ Commit markdown files"
          git push origin HEAD:master
```
