### ISSUE TITLE
Push without branch broken in 4.1 but works in 3.0.0

### ISSUE THREAD

**Issue by timwhite** [stefanzweifel/git-auto-commit-action#53]
**Version of the Action**
`v4.1.0`

**Describe the bug**
The push when no branch is specified just doesn't make it back to Github in V4.1.0 while it does work in v3.0.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Using v4.1.0 I expect after the commit the push back to the originating branch to occur. Instead I get an "everything is up to date" message.
https://github.com/TSSF-Asia-Pacific/communityobedience/runs/506933775?check_suite_focus=true#step:4:21

**Expected behaviour**
Instead of everything is up to date, it should show that it pushed back to the branch, like it does in v3.0.0 
https://github.com/TSSF-Asia-Pacific/communityobedience/runs/506938310?check_suite_focus=true#step:5:19

**Comment by stefanzweifel** [comment]
Hi Tim,

Thanks for pointing this out! Can confirm that the changes made in v4.1.0 no longer push the commit back to the right branch.

v4.0.0 still works as expected though.

**Comment by stefanzweifel** [comment]
Your issue has been fixed in #54. I've also tagged a new version: [v4.1.1](https://github.com/stefanzweifel/git-auto-commit-action/releases/tag/v4.1.1).
