### ISSUE TITLE
[4.x] Checkout and Commit to local temp branch

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/git-auto-commit-action#58]
**Is your feature request related to a problem? Please describe.**
It's quite hard to use the Action currently for both the `push` and `pull_request`-event.
For the `pull_request`-event, the `actions/checkout`-Action has to be configured in a specific way as the Action requires the repo to be checked out in a not-detached state.

**Describe the solution you'd like**
- Action should work independently on how `actions/checkout` is configured (with or without `ref`)
- Action should for all events checkout the the code in a temporary branch and commit to that branch

**Additional context**
See discussion in : https://github.com/stefanzweifel/git-auto-commit-action/issues/55#issuecomment-610931820

**Comment by stefanzweifel** [comment]
I've tinkered with this issue in #60. I couldn't find a good solution I'm happy with as described here: https://github.com/stefanzweifel/git-auto-commit-action/pull/60#issuecomment-615779260

I'm closing this issue too, as I don't see a great benefit of updating the Action to support this. 

Besides, pushing a commit in a workflow for `on: [push, pull_request]` seems like a bad idea in my opinion. Wouldn't the commit created by `push` interfere with the run for the `pull_request`-event?

**Comment by jasonkarns** [comment]
> Wouldn't the commit created by push interfere with the run for the pull_request-event?

push events fire on the fork repo whereas pull_request events fire in the origin (or upstream) repo. So they would only conflict if users are push branches directly to origin. But also, the use-case where I was attempting this had `if` conditionals on the steps, so there wasn't going to be a conflict anyway.

But I acknowledge the complexity probably isn't worth it, just to avoid a slight coupling with the "checkout config". Even if the pull/push typo is rectified, I think there will still be an issue. The detached-HEAD isn't the problem, but rather the fact that the checked-out commit is a _merge_ commit, and not the head of the PR. So if this push worked, it would not only push the new commit to the PR's branch head, it would also push a merge commit from the PR base. Which would be confusing and undesirable.
