### ISSUE TITLE
Issue with commit_options - error: unknown switch ` '

### ISSUE THREAD

**Issue by fungos** [stefanzweifel/git-auto-commit-action#61]
**Version of the Action**
`v4.1.3`

**Describe the bug**
Error during task execution: `error: unknown option ` --no-verify --signoff --verbose` as you can see (a workaround I've tried) here:
https://github.com/crossuo/shards/runs/606923804?check_suite_focus=true#step:4:17
or even this as suggested in the readme:
https://github.com/crossuo/shards/runs/606911285?check_suite_focus=true#step:4:17

**To Reproduce**
Copy-paste the first sample in readme with almost no modification

**Comment by stefanzweifel** [comment]
Thanks for reporting. I will look into this shortly!

**Comment by stefanzweifel** [comment]
Hm, first I thought the changes made in #59 broke the `commit_options`-input, but current master and current released version still fails.

Maybe GitHub changes something behind the scenes 🤔
Have to do more research.

**Comment by stefanzweifel** [comment]
Can confirm that this seems to be an issue on GitHubs side. Even older versions like v3.0.0 don't work anymore.

https://github.com/stefanzweifel/git-auto-commit-action-demo-app/runs/608305392#step:6:45

**Comment by fungos** [comment]
Yes, it is still broken. https://github.com/crossuo/shards/runs/608296418?check_suite_focus=true#step:4:17
Any way to enable actions debugging/echoing all commands?

**Comment by stefanzweifel** [comment]
@fungos You have to add a new secret to the repo with the name `ACTIONS_RUNNER_DEBUG` and value `true`. Actions will then output more debug mesages.

https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging

---

I just looked at this during lunch break. Will take a closer look later today.

**Comment by stefanzweifel** [comment]
Actually opened a thread in the community forums for this problem: https://github.community/t5/GitHub-Actions/Action-suddenly-can-t-pass-git-options-anymore/m-p/55111#M9435

**Comment by stefanzweifel** [comment]
@fungos 

I could find a solution to the problem. See #64.
I've already tested this in a test project. If you want to test it in your project too, you can use the following uses statement in your workflow:

```yaml
stefanzweifel/git-auto-commit-action@fix-61
```

I will tag a new version tomorrow.

**Comment by fungos** [comment]
Great! It worked now. https://github.com/crossuo/shards/runs/610317954?check_suite_focus=true#step:4:19

**Comment by stefanzweifel** [comment]
The issue has been fixed in [v4.1.5](https://github.com/stefanzweifel/git-auto-commit-action/releases/tag/v4.1.5).
