### ISSUE TITLE
remote: error: GH006: Protected branch update failed for refs/heads/master.        

### ISSUE THREAD

**Issue by sjurgis** [stefanzweifel/git-auto-commit-action#71]
**Version of the Action**
`v4.1.6`

**Describe the bug**
I'm not a repo owner so I don't really know how branch protection works. But it was repo owner that merged PR.

Just wanted to know is there is a setting or something that can whitelist an action to commit straight to master?

See log attached.
[5_Run stefanzweifelgit-auto-commit-action@v4.1.6.txt](https://github.com/stefanzweifel/git-auto-commit-action/files/4561820/5_Run.stefanzweifelgit-auto-commit-action%40v4.1.6.txt)

**Comment by stefanzweifel** [comment]
Protected branches allows repo owner to add "rules" for who or what is able to push to a branch. The [documentation](https://help.github.com/en/github/administering-a-repository/about-protected-branches) gives a good overview of whats possible.

> Just wanted to know is there is a setting or something that can whitelist an action to commit straight to master?

Unfortunately, it's not possible to circumvent protected branches.

**Comment by TomasVotruba** [comment]
I have the same problem. How can I modify the Github branch rule to allow pushes to it?

![image](https://user-images.githubusercontent.com/924196/81009120-53a5e700-8e54-11ea-98fd-3b3ab4290997.png)

This didn't help :/

**Comment by stefanzweifel** [comment]
@TomasVotruba The "Allow force pushes" setting would only work if the Action would use `git push --force`. Instead it does a normal `git push`. I will open an issue for that, so that the `git-push` command can also be modified with more options, if the user wants it.

However, I can guarantee if this would work. Searching the interwebs for "github actions push to protected branch" yields many results which will tell you, that this isn't possible ([See here](https://github.community/t5/GitHub-Actions/Allowing-github-actions-bot-to-push-to-protected-branch/m-p/34454/highlight/true#M1924)).

Maybe you can update the "Restrict who can push to matching branches" setting in your repo? I have no experience with protected branches, so I can't tell you, what you would have to enter there.

**Comment by lptn** [comment]
I use both "Allow force pushes" and `git push --force` but it doesn't work:
![image](https://user-images.githubusercontent.com/5278175/87848938-6ecdb200-c8ed-11ea-8e15-12ea7ff771be.png)
```yml
      - name: Commit updates to Rector's baseline
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "#12039 ✨ Update Psalm baseline"
          push_options: --force
          file_pattern: "psalm-baseline.xml"
```
```
INPUT_BRANCH value: 
M	psalm-baseline.xml
Your branch is up to date with 'origin/develop'.
INPUT_FILE_PATTERN: psalm-baseline.xml
INPUT_COMMIT_OPTIONS: 
[develop b50be08] #12039 ✨ Update Psalm baseline
 Author: {userslug} <{userslug}@users.noreply.github.com>
 1 file changed, 2 insertions(+), 42 deletions(-)
INPUT_TAGGING_MESSAGE: 
 No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: --force
remote: error: GH006: Protected branch update failed for refs/heads/develop.        
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.        
To https://github.com/{org}/{repo}
 ! [remote rejected] develop -> develop (protected branch hook declined)
error: failed to push some refs to 'https://github.com/{org}/{repo}'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by stefanzweifel** [comment]
@lptn Hm, could you try to create a personal access token, adding it to the workflow and trigger it again? 
We‘ve described this here: https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs

**Comment by lptn** [comment]
@stefanzweifel 
I've currently disabled branch protection and found another problem, related to `file_pattern`:
```
 Commit PHP code-style fixes0s
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: 
M	app/Providers/MailboxProvider.php
Your branch is up to date with 'origin/develop'.
INPUT_FILE_PATTERN: *.php
INPUT_COMMIT_OPTIONS: 
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   app/Providers/MailboxProvider.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	auth.json

no changes added to commit (use "git add" and/or "git commit -a")
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
```


step:
```
      - name: Commit PHP code-style fixes
        if: ${{ steps.fix_php.outcome == 'failure' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "#15000 ✨ Apply coding style fixes to PHP"
          push_options: --force
          file_pattern: "*.php"
```
without `file_pattern` it works well (but commits some extra files). I'm I doing something wrong? The same error I've got using `**/*.php` pattern

**Comment by stefanzweifel** [comment]
@lptn Using a Personal Access Token should work btw (https://github.com/stefanzweifel/git-auto-commit-action/issues/87#issuecomment-662907924)

But back to your `file_pattern`-problem:
I'm not 100% sure what the problem could be here. `**/*.php` is a valid pattern and works fine on my machine. [A StackOverflow](https://stackoverflow.com/a/9432242/3863449) answer mentions, that the file pattern has to be quoted to work for subdirectories. 🤔 

The Action doesn't do that currently: https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L48

Here are 2 links I've shared with other users before, when there was a problem with `file_pattern`

- https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
- https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec

I'm going to invest some time to update the README with a better examples on how to use `file_pattern` soon.

**Comment by lptn** [comment]
@stefanzweifel 
thanks a lot! Before writing my previous message, I've tested my patterns using `git` in terminal  and yes, they worked without any problems. I still don't know what's wrong, if I will find a solution or at least the cause of the problem – I'll share it here ;)

**Comment by iamrosada** [comment]
see this fix https://github.com/hexojs/hexo/issues/2817

**Comment by AlexFernandes-MOVAI** [comment]
see this action https://github.com/CasperWA/push-protected
