### ISSUE TITLE
Permission denied when trying to push

### ISSUE THREAD

**Issue by simonschaufi** [stefanzweifel/git-auto-commit-action#80]
Hi,
I have basically copied the example config from the readme into my project and I just can't make it work and I need some more eyes to spot the error. I have tried it with and without `GITHUB_TOKEN` but still no luck. Is there anything i need to configure in the settings? The only 2 protected branches are master and `2.0` but the workflow should work for any PR in my opinion.

**Version of the Action**
`v4`

**Used Workflow**

https://github.com/TYPO3/Surf/blob/d7aac7728fd887ff6397e9f3432d449b9706ba2b/.github/workflows/php_cs_fixer.yaml

**Additional context**

https://github.com/TYPO3/Surf/pull/403/checks?check_run_id=700669827

```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: feature/add-project-base-path
Already on 'feature/add-project-base-path'
M	src/Task/Test/HttpTestTask.php
Your branch is up to date with 'origin/feature/add-project-base-path'.
INPUT_FILE_PATTERN: .
INPUT_COMMIT_OPTIONS: 
[feature/add-project-base-path 1f3600b] Apply php-cs-fixer changes
 Author: simonschaufi <simonschaufi@users.noreply.github.com>
 1 file changed, 1 deletion(-)
INPUT_TAGGING_MESSAGE: 
 No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
fatal: unable to access 'https://github.com/TYPO3/Surf/': The requested URL returned error: 504
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by stefanzweifel** [comment]
Hi there,

The workflow file looks fine and should work as expected. 🤔 
In the log I see, that the Action failed due to a server error on GitHub:

> fatal: unable to access 'https://github.com/TYPO3/Surf/': The requested URL returned error: **504**

Maybe this is related to this Incident from yesterday: https://www.githubstatus.com/incidents/6tcfpztf6j9m

Could you try running your workflow again?
(Some of my own scheduled Workflows using this Action failed yesterday with a similar error, but succeeded in the last couple of hours.)

---

Sidenote: The `GITHUB_TOKEN` input on the Action-step is not necessary and could be removed

```diff
            -   name: Commit changed files
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Apply php-cs-fixer changes
                    branch: ${{ github.head_ref }}
-                env:
-                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by simonschaufi** [comment]
Thanx, the workflow works now fine again. In which case do I need the GITHUB_TOKEN?

**Comment by stefanzweifel** [comment]
@simonschaufi Great!
You don't need the GITHUB_TOKEN for those very simple workflows.

However, if you would like to trigger workflows based on the created commit of this action, you would need to create a personal access token. 
You can find more information about this special use case in the README: https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs

**Comment by simonschaufi** [comment]
thank you very much for your help!

**Comment by danielo515** [comment]
For me setting this in repo settings under actions > general was required:

![image](https://user-images.githubusercontent.com/2270425/219853004-fe07ae69-c543-4239-ab35-da953ed4f6d6.png)


After that it worked out of the box

**Comment by stefanzweifel** [comment]
For others who might come across this issue from a Google search:

You can either change the default permission of the GITHUB_TOKEN as @danielo515 mentioned, or you can set the permissions in the workflow file.

```yaml
name: Format

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Other steps that change files in the repository

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
```

See the usage section in the docs: https://github.com/stefanzweifel/git-auto-commit-action#usage.

You might run into permission issues, as GitHub changed the default permission of the GITHUB_TOKEN at the beginning of February to read-only: https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/

**Comment by danielo515** [comment]
Awesome! Thanks for the information.
