### ISSUE TITLE
More details on the patterns accepted for file_pattern: 

### ISSUE THREAD

**Issue by didier-durand** [stefanzweifel/git-auto-commit-action#83]
Could you provide more details in the documentation page about the patterns that are accepted:1 example for all the files and directories under a given directory would be nice. 

Do you follow the Apache Ant file pattern ( https://ant.apache.org/manual/Types/patternset.html ) or another one ?

I want to commit back all files generated in the /data subdirectory of my project. Is file_pattern: data/* correct for this purpose?

Thanks!

Didier

**Comment by stefanzweifel** [comment]
Hi Didier 👋

The action does not implement it's own pattern. 

The given input [is passed](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L48) to `git-add` as the [`pathspec`](https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203) argument. There's more information about pathspec in the  [git Glossary](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec).

> I want to commit back all files generated in the /data subdirectory of my project. Is file_pattern: data/* correct for this purpose?

Do add all file in a subdirectory `file_pattern: data/` should suffice.


I'm not familiar with the Apache Ant file pattern so I can't really answer this particular question :(

**Comment by didier-durand** [comment]
Very precise answer. Thanks Stefan!
