### ISSUE TITLE
pass dynamic message

### ISSUE THREAD

**Issue by wenerme** [stefanzweifel/git-auto-commit-action#89]
**Is your feature request related to a problem? Please describe.**
want to use generated message

**Describe the solution you'd like**
read from file

**Describe alternatives you've considered**
none

**Additional context**

this https://github.com/wenerme/charts ci use auto-commit, want to use generate message like `redis 1.1.1 -> 1.1.2` instead just `update mirror`

**Comment by stefanzweifel** [comment]
This should be possible by adding an additional step into your workflow.
Below is an example which should work.

```diff
 # ...
     
+    - name: Generate Commit Message
+      run: |
+        echo "##[set-output name=message;]$(npm run generate-message)"
+      id: generate_commit_message
 
     - uses: stefanzweifel/git-auto-commit-action@v4
       with:
+        commit_message: ${{ steps.generate_commit_message.outputs.message) }}
         commit_user_name: GitHub Actions
         commit_user_email: wenermail@gmail.com
         commit_author: GitHub Actions <wenermail@gmail.com>
 
 # ...
```

The step "Generate Commit Message" needs an `id` and pushes the result of `npm run generate-message` to the output "variable" `message`.
The value is the available in other steps as `${{ steps.generate_commit_message.outputs.message) }}`.
